version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1

jobs:
  build-data-container:
    executor: gcp-gcr/default
    parameters:
      repo:
        description: Name of the repository containing the databuild
        type: string
      branch:
        description: Name of the branch of the data build
        type: string
      workflow:
        description: Name of the workflow to be startd
        type: string
    steps:
      - deploy:
          name: Send webhook to start datacontainer build
          command: |
            curl -u ${DATA_CONTAINER_CIRCLE_APIKEY}: \
                -d build_parameters[CIRCLE_JOB]=<<parameters.workflow>>
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/<<parameters.repo>>/tree/<<parameters.branch>>

workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: opentripplanner
          registry-url: eu.gcr.io
          filters:
            branches:
              only: hsldevcom
      - build-data-container:
          repo: matkahuolto-data-container
          branch: otp-1
          workflow: build_and_push_image
          filters:
            branches:
              only: hsldevcom

