version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.11.0

workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: opentripplanner-2
          registry-url: eu.gcr.io
          tag: $CIRCLE_SHA1
      - gcp-gcr/add-image-tag:
          filters:
            branches:
              only: master
          requires:
            - gcp-gcr/build-and-push-image
          image: opentripplanner-2
          registry-url: eu.gcr.io
          source-tag: $CIRCLE_SHA1
          target-tag: latest

  production-tag:
    jobs:
      - gcp-gcr/add-image-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /production-\d.*/
          image: opentripplanner-2
          registry-url: eu.gcr.io
          source-tag: $CIRCLE_SHA1
          target-tag: prod
