version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1

workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: opentripplanner
          registry-url: eu.gcr.io